import pandas as pd
import numpy as np
import logging

logger = logging.getLogger('StatFantasy_Stats_Calculator')
logging.basicConfig(level=logging.INFO)

class StatsCalculator:
    """
    Data Specialist Module:
    Calculates advanced stats (xG, xA, Form, Composite Scoring) required by the Architect schema.
    Takes dataframes generated by fpl_pipeline.py as inputs.
    """

    def __init__(self, players_df: pd.DataFrame, fixtures_df: pd.DataFrame):
        self.players_df = players_df
        self.fixtures_df = fixtures_df

    def merge_external_xg_xa(self, player_stats_df: pd.DataFrame) -> pd.DataFrame:
        """
        Mock implementation. In production, this would hit the Understat or FBref API,
        match player names, and append actual expected goals (xG) and expected assists (xA).
        """
        logger.info("Merging external xG/xA data (mock implementation).")
        # Simulating data merge
        np.random.seed(42)
        # Assigning random xG (0.0 to 1.1) and xA (0.0 to 0.8) based on element_type (Positional weights)
        player_stats_df['xG'] = np.where(player_stats_df['element_type'].isin([3, 4]), 
                                         np.random.uniform(0.1, 1.2, len(player_stats_df)), 
                                         np.random.uniform(0.0, 0.2, len(player_stats_df)))
        
        player_stats_df['xA'] = np.where(player_stats_df['element_type'].isin([2, 3]), 
                                         np.random.uniform(0.1, 0.8, len(player_stats_df)), 
                                         np.random.uniform(0.0, 0.3, len(player_stats_df)))
        
        return player_stats_df

    def calculate_form_momentum(self, player_stats_df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculates the form score. 'Form' in FPL is the average points over the last 30 days.
        Here we create a synthetic momentum score incorporating xG/xA and recent minutes played.
        """
        logger.info("Calculating player Form Momentum.")
        
        # Example synthetic calculation (Mock logic requiring historical matches data normally)
        # We assume players_df has a 'form' and 'ict_index' as base 
        try:
            base_form = pd.to_numeric(player_stats_df.get('form', 0.0))
            ict_index = pd.to_numeric(player_stats_df.get('ict_index', 0.0))
        except Exception:
            base_form = 0.0
            ict_index = 0.0

        # Weighted calculation (Form * 0.4) + (ICT * 0.3) + (xG+xA * 0.3)
        xg_xa_weight = player_stats_df.get('xG', 0) + player_stats_df.get('xA', 0)
        
        player_stats_df['custom_form_momentum'] = (
            (base_form * 0.4) + 
            (ict_index * 0.3) + 
            (xg_xa_weight * 5.0)  # Scaling up xG/xA to match FPL score ranges ~0-10
        ).round(2)
        
        return player_stats_df

    def compute_composite_score(self) -> pd.DataFrame:
        """
        The main pipeline method for calculating advanced stats per player.
        """
        df = self.players_df.copy()
        df = self.merge_external_xg_xa(df)
        df = self.calculate_form_momentum(df)
        
        logger.info("Advanced stats calculation complete.")
        return df

if __name__ == "__main__":
    # Example test runner
    dummy_players = pd.DataFrame({
        'id': [1, 2, 3],
        'web_name': ['Haaland', 'Salah', 'Saliba'],
        'element_type': [4, 3, 2],
        'form': ['8.5', '7.2', '4.0'],
        'ict_index': ['15.2', '18.1', '3.5']
    })
    
    calculator = StatsCalculator(players_df=dummy_players, fixtures_df=pd.DataFrame())
    enriched_df = calculator.compute_composite_score()
    
    print("\n--- Enriched Player Stats sample ---")
    print(enriched_df.head())
